<?php
    session_start();

    //1. current status of the application
    //2. Do some action like give remarks if the application has been sent back..
    //only if application's current node is this person
    //3. Be able to withdraw an application
    //4. Be able to view the current status of the application
    //5. Display the history of this particular leave in tabular format

    if($_SESSION['loggedin']==false){
        header("Location: ./login.php");
    }

    include('./index.php');
    include('./functions.php');


    $faculty_id = $_SESSION['username'];
    $leave_id = $_GET['leave_id'];

    $leave_r = get_leave_by_id($db_connection, $leave_id);
    $route_r = get_route_by_id($db_connection, $leave_r['leave_route_id']);
    $faculty_r = get_faculty_by_id($db_connection, $faculty_id);

    $post_rank = $faculty_r['post_rank'];

    if($post_rank>10 && $post_rank<100){
        $post_rank=10;
    }

    $allowed = false;//true if the current user is allowed access to this leave

    if($faculty_id==$leave_r['faculty_id']){
        $allowed=true;
    }
    else if(in_array($post_rank, $route_r)){
        $allowed=true;
    }

    if($allowed==false){
        Header('Location: ./access_not_allowed.php');
    }

    $transactions_q = pg_query($db_connection, "SELECT * FROM leave_history WHERE leave_id='".$leave_id."' ORDER BY(transaction_time) DESC");
?>

<body>
    <div class="container">
        <div class="row">
            <!-- <div class="col-md-2"></div> -->
            <div class="col-md-12">
                <?php
                    echo "<br><p><small><strong>Leave ID - ".$leave_id."</strong></small></p>";
                    echo "<p><small>Faculty ID - ".$leave_r['faculty_id']."</small></p>";
                    echo "<p><small>Start Date of Leave - ".$leave_r['start_date']."</small></p>";
                    $effective_num_days = $leave_r['num_days']-1;
                    echo "<p><small>End Date of Leave - ".date('Y-m-d', strtotime($leave_r['start_date'].'+'.$effective_num_days.'days'))."</small></p>";
                    echo "<p><small>Purpose of Leave - ".$leave_r['leave_purpose']."</small></p>";

                ?>
            </div>
            <!-- <div class="col-md-2"></div> -->
        </div>
        <div class="row" >
            <div class='col-md-12'>
                    <?php
                        $i=0;
                        $num_rows = pg_num_rows($transactions_q);
                        while($transactions_r = pg_fetch_assoc($transactions_q)){
                            $origin_post_rank = $transactions_r['start_post_id'];
                            // $destination_faculty_id = $transactions_r['end_faculty_id'];
                            $dt = $transactions_r['transaction_time'];
                            $status = $transactions_r['status'];
                            $remarks = $transactions_r['remarks'];

                            if($i==$num_rows-1){
                                $action='Generated by '.$leave_r['faculty_id'];
                            }

                            if($i==0){

                                if($faculty_id==$leave_r['faculty_id'] && $status=='sent for review'){
                                    echo "<form class='form-inline'  method='post'>";
                                    echo "<label for='remarks' style='margin-right:0.2em;'><small>Remarks</small></label>";
                                    echo "<input type='text' style='font-size:0.8em; width:50%; margin-right:0.4em;' placeholder='Enter Remarks' name='remarks' id='remarks' required>";
                                    echo "<input type='hidden' name='transaction_id' id='transaction_id' value='".$transactions_r['transaction_id']."'>";
                                    echo "<input type='submit'  style='margin-right:0.4em;' class='btn btn-sm btn-success' formaction='/send_after_review.php' value='Send Again'></form>";
                                }

                                echo "<table class='table table-striped table-dark'>";

                                echo "<thead><tr><th scope='col'>Action</th><th scope='col'>Start Faculty Origin</th><th scope='col'>Destination Faculty</th><th scope='col'>Date & Time</th><th scope='col'>Remarks</th></tr></thead>";
                                // echo "<thead><tr><th scope='col'>Action</th><th scope='col'>Date & Time</th><th scope='col'>Remarks</th></tr></thead>";

                                $action_taker = get_faculty_by_post($db_connection,$transactions_r['start_post_id']);
                                if($transactions_r['start_post_id']==0){
                                    $action_taker=$leave_r['faculty_id'];
                                    $action =  $status." by ".$action_taker;
                                }
                                else{
                                    $action =  $status." by ".$action_taker['faculty_id'];
                                }
                            }
                            else{
                                $action_taker = get_faculty_by_post($db_connection,$transactions_r['start_post_id']);
                                if($transactions_r['start_post_id']==0){
                                    $action_taker=$leave_r['faculty_id'];
                                    $action =  $status." by ".$action_taker;

                                }
                                else{
                                    $action =  $status." by ".$action_taker['faculty_id'];
                                }
                            }
                            $start_faculty=get_faculty_by_post($db_connection,$transactions_r['start_post_id'])['faculty_id'];
                            if($transactions_r['start_post_id']==0){
                                $start_faculty=$leave_r['faculty_id'];
                            }

                            $end_faculty=get_faculty_by_post($db_connection,$transactions_r['end_post_id'])['faculty_id'];
                            if($transactions_r['end_post_id']==0){
                                $end_faculty=$leave_r['faculty_id'];
                            }
                                echo "<tr>";
                                echo "<td>".$status."</td>";
                                echo "<td>".$start_faculty."</td>";
                                echo "<td>".$end_faculty."</td>";
                                echo "<td>".$dt."</td>";
                                echo "<td>".$remarks."</td>";
                                echo "</tr>";

                            $i++;
                        }
                    ?>

                </table>
            </div>

        </div>
        
    </div>
</body>